version: 2

## Customize the test machine
jobs:
    build:
      docker:
      - image: circleci/openjdk:8-jdk-browsers

general:
  build_dir: /SuiteAutomationTest


## Customize dependencies
dependencies:
  pre:
    - mvn dependency:resolve
    - sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0/bin/java
    - sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
    - echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.circlerc

## Customize test commands
test:
  override:
    - mvn clean test install

